name: Aws EC2
on: 
    [push, workflow_dispatch]
permissions: 
   id-token: write
   contents: read
jobs:
    EC2_Initialize:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
              with:
                 path: EC2
             
            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.1.7"

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::348420498265:role/github_action_test
                role-session-name: sampleroesession
                aws-region: us-east-1

            - name: version check
              run: terraform version

            - name: initialize the dir
              run: terraform init

            - name: initialize the dir
              run: terraform plan
              

              

    