name: Aws vpc 
on: 
    [push, workflow_dispatch]
jobs:
    Inititalize:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
              with: 
                path: ./AWS_VPC

            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.1.7"

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: us-east-1
            - name: dir
              run: ls && pwd

            - name: version check
              run: terraform version

            - name: initialize the dir
              run: ls && pwd && terraform init && terraform plan

              

    