name: Aws vpc 
on: 
    [push, workflow_dispatch]
jobs:
    Inititalize:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
              with: 
                path: ./AWS_VPC

            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.1.7"
                  
            - name: version check
              run: terraform version

            - name: initialize the dir
              run: terraform init


    